YAML
  deploy_job:
    runs-on: ubuntu-latest
    needs: test_job
    # Указываем специальный Docker-контейнер для этой задачи
    container:
      image: alpine:latest # Это супер-легкий и популярный в DevOps Linux-образ
    steps:
      - name: Download Log for Deploy
        uses: actions/download-artifact@v4
        with:
          name: pipeline-logs

      - name: Run Deploy
        run: |
          echo "Deploying project $PROJECT_NAME..."
          echo "Deploy stage done" >> $LOG_FILE
          echo "--- Final Log Content ---"
          cat $LOG_FILE
          echo "--- Checking system info inside container ---"
          cat /etc/os-release # Эта команда покажет, что мы внутри Alpine Linux, а не Ubuntu!
